### ISSUE TITLE
Integrate ideas of Bowker and Star

### ISSUE THREAD

**Issue by amyjko** [amyjko/foundations-of-information#15]
Bowker, G. C., & Star, S. L. (2000). Sorting things out: Classification and its consequences.

At a minimum, cite it, but probably also address it early on in relation to knowledge organization.

**Comment by orcmid** [comment]
I found this to be helpful: https://www.ics.uci.edu/~gbowker/classification/
There is one occurrence of "ontology." The extensive demonstration of classification issues and also the situations when something is undistinguishable because classification doesn't (yet) permit it or that classification submerges it are interesting.  There is ample illustration of the use of categories as governing the framing of the terms of discussion that prevail.

**Comment by amyjko** [comment]
Added citation.
