### ISSUE TITLE
Ch. 4 plaintext characters are rendering as "plaintext"

### ISSUE THREAD

**Issue by mxwe** [amyjko/foundations-of-information#77]
![unknown](https://user-images.githubusercontent.com/35820392/161641536-640877b0-841d-4a80-98c5-4d6c0574a8cd.png)

**Comment by amyjko** [comment]
Oops, fixed!

**Comment by orcmid** [comment]
Um, sorry, ASCII was not the first such encoding.  It's also a 7-bit encoding.  ASCII was relatively late and as described, was an American (that is, USA) specification although transposed eventually into ISO 646 and, now, the first 128 codes of the Unicode Standard (and also the first 128 codes in the UTF8 encoding, the only ones in a single octet/byte).

The treatment here, with decimal values of ASCII codes is fine.  There just needs to be something smoother about choosing to illustrate it that doesn't create unfortunate folk wisdom about the origin of numeric encoding of character sets, which predates ASCII and even commercial digital computers.  I also wouldn't call them "8-bit numbers" since the ASCII codes are from 0 through 127, represented in binary notation.

=== Background  

The IBM BCD (binary-coded data) 6 bit code was morphed into the 8-bit EBCDIC code around the same time as ASCII was developing.  EBCDIC was featured with the introduction of the IBM System/360. ASCII was sought originally for telecommunication purposes (and probably anybody-but-IBM) and took further hold as teletype terminals became prominent in minicomputer systems.  We can credit the Digital Equipment VT52 terminal and other developments (such as the PDP11) for the entrenchment of ASCII and its derivatives as well as its preservation in a portion of Unicode.  Hence to Unix systems, etc.  It would be interesting to know what was decisive about having ASCII and relatives on the original IBM PC.

There were other 6-bit character codes beside BCD and I managed to work with a couple of those in the late 50s, early 60s.

**Comment by amyjko** [comment]
Thank you Dennis; this history is probably out of scope, but it's worth some additional clarification for accuracy. But this isn't quite the right issue to report this; I'll move it to a new issue.

**Comment by orcmid** [comment]
Sorry, I did a TMI.  I don't know when you get into bits from the quoted passage, where you first distinguishing between numbers and numeric encoding, and then start talking about 8-bit seqences.

You could stay at a level where you still talk about numbers and don't get into bits at all, and just say something like "the widely used ASCII standard represention of characters by numbers".   If you can meaningfully say "numbers typically coded in 8-bit binary elements" or something.  

I will go back for the actual context, but my thought is about staying at the same level for the reader.

**Comment by orcmid** [comment]
OK, I got it.  Concerning ASCII, I wouldn't attempt history.  Also, I would not say _unsigned_ binary in the example of a text sequence.  Just binary.  

I would also put this before the treatment of floating point representations.  In my experience, the coding of text can be a stumbling point, especially when we encounter "123"` and `123` often being different.  Getting , the first being taken as the characters, the second as a numeral.   This sort of thing needs to be solid.  

It seems to me that treatment of floating-point is more problematic, especially because conversions both in and out are approximations to some degree and so are the operations.  Trickier business.  Ideally, to be encountered less often by most of your readers.
